const topCitiesSpain = [
  { label: 'Madrid', year: null },
  { label: 'Barcelona', year: null },
  { label: 'Valencia', year: null },
  { label: 'Sevilla', year: null },
  { label: 'Zaragoza', year: null },
  { label: 'Málaga', year: null },
  { label: 'Murcia', year: null },
  { label: 'Palma de Mallorca', year: null },
  { label: 'Las Palmas de Gran Canaria', year: null },
  { label: 'Bilbao', year: null },
  { label: 'Alicante', year: null },
  { label: 'Córdoba', year: null },
  { label: 'Valladolid', year: null },
  { label: 'Vigo', year: null },
  { label: 'Gijón', year: null },
  { label: 'Hospitalet de Llobregat', year: null },
  { label: 'La Coruña', year: null },
  { label: 'Granada', year: null },
  { label: 'Vitoria-Gasteiz', year: null },
  { label: 'Elche', year: null },
  { label: 'Oviedo', year: null },
  { label: 'Santa Cruz de Tenerife', year: null },
  { label: 'Badalona', year: null },
  { label: 'Cartagena', year: null },
  { label: 'Terrassa', year: null },
  { label: 'Jerez de la Frontera', year: null },
  { label: 'Sabadell', year: null },
  { label: 'Móstoles', year: null },
  { label: 'Alcalá de Henares', year: null },
  { label: 'Pamplona', year: null },
  { label: 'Fuenlabrada', year: null },
  { label: 'Almería', year: null },
  { label: 'San Sebastián', year: null },
  { label: 'Leganés', year: null },
  { label: 'Getafe', year: null },
  { label: 'Burgos', year: null },
  { label: 'Santander', year: null },
  { label: 'Castellón de la Plana', year: null },
  { label: 'Albacete', year: null },
  { label: 'Salamanca', year: null },
  { label: 'Logroño', year: null },
  { label: 'Huelva', year: null },
  { label: 'Marbella', year: null },
  { label: 'Lleida', year: null },
  { label: 'Tarragona', year: null },
  { label: 'León', year: null },
  { label: 'Cádiz', year: null },
  { label: 'Jaén', year: null },
  { label: 'Ourense', year: null },
  { label: 'Girona', year: null },
];

export default topCitiesSpain;